### Get All countries
GET localhost:8080/countries
Accept: application/json



### Get coutry cities
GET localhost:8080/country-cities?countryid=1
Accept: application/json




### Creat Feedback
POST localhost:8080/
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="feedback"
Content-Type: application/json

{
  "user_phone": "992887585005",
  "city_id": 2,
  "massage": "Хочу у себя в городе видеть нормальных людей"
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="t.jpg"
Content-Type: application/octet-stream

< D:\Мои фотки\test.jpg
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="t.jpg"
Content-Type: application/octet-stream

< D:\Мои фотки\test.jpg

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="t.jpg"
Content-Type: application/octet-stream

< D:\Мои фотки\test.jpg
--WebAppBoundary--


###Creat feedback just with text
POST localhost:8080/
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="feedback"
Content-Type: application/json

{
  "user_phone": "992887585005",
  "city_id": 1,
  "massage": "У меня трисомия 21 пары"
}



### Get all feedbacks
GET localhost:8080/all-feedbacks?page=1&limit=4&term=false
Accept: application/json


###Search feedbacks by user_phone
GET localhost:8080/search?page=1&limit=3&phone=992887585005
Accept: application/json